#+TITLE: Lab02 Tests
#+TESTY: PREFIX="lab2"
#+TESTY: REPORT_FRACTION=1
#+TESTY: SHOW=1

* QUIZ: QUESTIONS.txt
This test determines if the answers in QUESTIONS.txt are correct. This file must
be edited so that the correct ( ) choices are replaced with (X) AND no other
changes are made to the file. If you are confident in your answers but think you
may have made inadvertent changes to QUESTIONS.txt, you can try restoring it
with the provided QUESTIONS.txt.bk file.

The correct output for the test should be 
>> ./test_quiz_filter QUESTIONS.txt | sha256sum -C QUESTION.sha256
-: OK

Note: the sha256sum program is used to verify and must be installed to work.

#+TESTY: use_valgrind=0
#+BEGIN_SRC sh
>> ./test_quiz_filter QUESTIONS.txt | sha256sum -c QUESTIONS.sha256
-: OK
#+END_SRC


* CODE: copy_file read_last_ints Tests

** copy_file With Text File
Attempts to copy a text file.
#+TEST: use_valgrind=1
#+BEGIN_SRC sh
>> rm -f numbers_copy.txt
>> ./copy_file numbers.txt numbers_copy.txt
>> diff numbers.txt numbers_copy.txt
#+END_SRC

** copy_file With Binary File
Attempts to copy a binary file.
#+TEST: use_valgrind=1
#+BEGIN_SRC sh
>> rm -f numbers_copy.bin
>> ./copy_file numbers.bin numbers_copy.bin
>> diff numbers.bin numbers_copy.bin
#+END_SRC

** read_last_ints Test 1
Attempts to read the last 11 ints from the file numbers.bin
#+TEST: use_valgrind=1
#+BEGIN_SRC sh
>> ./read_last_ints numbers.bin 11
3647
2433
1624
1266
505
571
1648
255
900
1801
1694
#+END_SRC

** read_last_ints Test 2
Attempts to read the last int from the file numbers.bin
#+TEST: use_valgrind=1
#+BEGIN_SRC sh
>> ./read_last_ints numbers.bin 1
1694
#+END_SRC

** read_last_ints Test 3
Attempts to read the last 19 ints from the file numbers.bin
#+TEST: use_valgrind=1
#+BEGIN_SRC sh
>> ./read_last_ints numbers.bin 19
3580
960
3621
3725
1749
1465
2472
3772
3647
2433
1624
1266
505
571
1648
255
900
1801
1694
#+END_SRC
