#+TITLE: Lab04 Tests
#+TESTY: PREFIX="lab"
#+TESTY: REPORT_FRACTION=1
# #+TESTY: SHOW=1

* QUIZ: QUESTIONS.txt
This test determines if the answers in QUESTIONS.txt are correct. This
file must be edited so that the correct ( ) choices are replaced with
(X) AND no other changes are made to the file. If you are confident in
your answers but think you may have made inadvertent changes to
QUESTIONS.txt, you can try restoring it with the provided
QUESTIONS.txt.bak file.

The correct output for the test should be 
>> ./test_quiz_filter QUESTIONS.txt | sha256sum -c QUESTIONS.sha256
-: OK

Note: the sha256sum program is used to verify and must be installed to work.

#+TESTY: use_valgrind=0

#+BEGIN_SRC sh
>> ./test_quiz_filter QUESTIONS.txt | sha256sum -c QUESTIONS.sha256
-: OK
#+END_SRC


* CODE: redirect_child
Runs the program ~redirect_child~ in a few cases to ensure that it
produces the correct output and has a child process that redirects its
standard output into a file.

Note: runs a couple times and checks that the command line argument
argv[1] is used as the output file where the child writes its output.

#+BEGIN_SRC sh
>> ./redirect_child out1.tmp
Child complete, return code 0
>> cat out1.tmp
25 25 66 nums.txt
#+END_SRC

#+BEGIN_SRC sh
>> ./redirect_child out2.tmp
Child complete, return code 0
>> cat out2.tmp
25 25 66 nums.txt
#+END_SRC
